export const certifications = [
	{
		id: "ad345asdfasdfs4rtt",
		title: "Meta Back-End Developer Specialization",
		issued_by: "Emitido por Coursera | Autorizado por Meta",
		link: "https://www.coursera.org/account/accomplishments/specialization/C3RDH2G9WJHN",
		icon: "meta_backend",
		tags: [
			"Django",
			"Python",
			"API endpoints",
			"MySql",
			"GitHub",
			"Data Structure",
			"Bash",
			"Web Development",
		],
	},
	{
		id: "ad345asdfafdsfsdfasdfs4rtt",
		title: "Meta Back-End Developer Specialization",
		issued_by: "Emitido por Coursera | Autorizado por Meta",
		link: "https://www.coursera.org/account/accomplishments/specialization/C3RDH2G9WJHN",
		icon: "meta",
		tags: ["backend", "frontend"],
	},
	{
		id: "ad345asdfafsdfsdfsdfsdfs4rtt",
		title: "Meta Back-End Developer Professional",
		issued_by: "Emitido por Coursera | Autorizado por Meta",
		link: "https://www.coursera.org/account/accomplishments/specialization/C3RDH2G9WJHN",
		icon: "meta",
		tags: ["backend", "frontend"],
	},
];
