export const certifications = [
	{
		id: "635a6f5e-cdab-446f-9408-aa2e4e81371c",
		title: "Meta Back-End Developer Specialization",
		issued_by: "Emitido por Coursera | Autorizado por Meta",
		link: "https://www.coursera.org/account/accomplishments/specialization/C3RDH2G9WJHN",
		icon: "meta_backend",
		tags: [
			"Django",
			"Python",
			"API endpoints",
			"MySql",
			"GitHub",
			"Data Structure",
			"Bash",
			"Web Development",
		],
	},
	{
		id: "cb4042c6-f603-4b21-95af-456bc3435cd5",
		title: "AWS Fundamentals",
		issued_by: "Emitido por Coursera | Autorizado por AWS",
		link: "https://coursera.org/share/6120f9bb71961e6d433daa3732a41421",
		icon: "aws",
		tags: ["Cloud computing", "AWS IAM", "AWS security", "Arquitectura software", "AWS console"],
	},
	{
		id: "11B87266C145",
		title: "Patrones de diseño en Symfony",
		issued_by: "Emitido por SymfonyCasts",
		link: "https://symfonycasts.com/certificates/11B87266C145",
		icon: "symfony",
		tags: ["PHP", "Symfony", "Patrones de diseño", "Arquitectura software"],
	},
	{
		id: "DF4615E9C138",
		title: "Dominar las relaciones en Doctrine - Symfony",
		issued_by: "Emitido por SymfonyCasts",
		link: "https://symfonycasts.com/certificates/DF4615E9C138",
		icon: "symfony",
		tags: ["PHP", "Symfony", "Doctrine", "ORM"],
	},
	{
		id: "D1F88168C143",
		title: "PHPUnit en Symfony",
		issued_by: "Emitido por SymfonyCasts",
		link: "https://symfonycasts.com/certificates/D1F88168C143",
		icon: "symfony",
		tags: ["PHP", "Symfony", "PHPUnit", "Testing"],
	},
	{
		id: "BA8E852B2C91",
		title: "ReactJS en Symfony",
		issued_by: "Emitido por SymfonyCasts",
		link: "https://symfonycasts.com/certificates/BA8E852B2C91",
		icon: "symfony",
		tags: ["PHP", "Symfony", "ReactJS", "Webpack"],
	},
	{
		id: "BB9D67A8C122",
		title: "Principios SOLID en Symfony",
		issued_by: "Emitido por SymfonyCasts",
		link: "https://symfonycasts.com/certificates/BB9D67A8C122",
		icon: "symfony",
		tags: ["PHP", "Symfony", "Principios SOLID", "Arquitectura software"],
	},
	{
		id: "74478319C139",
		title: "Autenticación en Symfony 5",
		issued_by: "Emitido por SymfonyCasts",
		link: "https://symfonycasts.com/certificates/74478319C139",
		icon: "symfony",
		tags: ["PHP", "Symfony", "Autenticación", "Seguridad"],
	},
	{
		id: "49e6f099-b593-482d-b996-5d49e8e48c80",
		title: "Curso de Symfony Framework",
		issued_by: "Emitido por Platzi",
		link: "https://platzi.com/p/serodas/curso/1901-symfony-framework/diploma/detalle/",
		icon: "platzi",
		tags: ["PHP", "Symfony", "Formularios"],
	},
];
